### PR TITLE
Enemy stats for the Battle generator

### PR DESCRIPTION
**Pull request by nanux**
Unfortunately, I wasn't able to test it locally but it should be just a simple string change so I am not expecting issues.

I have also aligned the columns so it was easier to read and fill.

### CODE REVIEW

**Comment by nanux** [comment]
@sheibeck I am really sorry but I haven't realised this hasn't been merged before I have deleted the OAuth from the repo to test my local development. Can you either revert the PR or remove `de42a3f` commit?

**Comment by sheibeck** [comment]
Yeah, don't worry about it. I thought maybe you discovered something that I
was missing :D

**Comment by sheibeck** [comment]
I added a test user on the staging server. Let's see if you can login using
this user. Don't use the google login, but type this in the username/pass
fields:
u: ***@***.***
p: 5ParsecsTest!

This should entirely circumvent the google auth, and just use the normal
authentication for AWS Cognito. I logged in both on localhost and it let me
in. Let me know what you're seeing on your end when you fail to
authenticate. Just trying to determine if it's just an invalid user, or
some deeper issue.

-Sterling

**Comment by sheibeck** [comment]
@nanux I released the updated enemy stats into production. Thank you!!

**Pull request merged**
